### ISSUE TITLE
type of optical flow used

### ISSUE THREAD

**Issue by bimalsapkotaa** [pimoroni/pmw3901-python#13]
Does anybody know what kind of optical flow algorithm is used here? Dense or sparse?

**Comment by Gadgetoid** [comment]
I don't think so- the manufacturer is very guarded about the secret sauce that makes this thing tick.

... *very* guarded:

https://github.com/pimoroni/pmw3901-python/blob/bf798f6d58a1527563822d152d2650cc72e06e09/library/pmw3901/__init__.py#L170-L177

I'll ask our engineers, though, just in case!

**Comment by Gadgetoid** [comment]
Engineers have no better idea, I'm afraid.
