### ISSUE TITLE
Offset from center of mass

### ISSUE THREAD

**Issue by bimalsapkotaa** [pimoroni/pmw3901-python#14]
Im using this sensor on a turtlebot3 burger to find the odometry. For this I have mounted the sensor at the front of the robot facing downwards. I now want to compensate for the fact that this sensor isn't mounted at the center of mass of the vehicle, because when the turtlebot rotates around its axis that goes through the center of mass, the optical sensor says that there's movement in x and y. Are there any parameter in the optical flow sensor that I can set to compensate for this offset? Any other ways to get around this problem?

**Comment by Gadgetoid** [comment]
There's no way to configure the flow sensor for this, as far as I'm aware, it's pretty minimally documented and full of manufacturer secret sauce.

There will be a sensible answer to this question somewhere, but it's rooted more in maths/geometry than programming and I can't quite figure out how you might accomplish it.
