### ISSUE TITLE
Error when running Example files with Raspberry Pi

### ISSUE THREAD

**Issue by Andrew123098** [pimoroni/pmw3901-python#19]
Hello! 
I am using the Pimoroni PMW3901 breakout board with a Raspberry Pi Zero 2 W and running into trouble using the example scripts you provide in this GitHub repository. In short, when I run the code I get the following error:

`File "/home/pi/Desktop/dronepi/Examples/OF_motion.py", line 28, in <module>
    flo = SensorClass(spi_port=0, spi_cs_gpio=BG_CS_FRONT_BCM if args.spi_slot == 'front' else BG_CS_BACK_BCM)
  File "/usr/local/lib/python3.9/dist-packages/pmw3901/__init__.py", line 49, in __init__
    raise RuntimeError("Invalid Product ID or Revision for PMW3901: 0x{:02x}/0x{:02x}".format(product_id, revision))
RuntimeError: Invalid Product ID or Revision for PMW3901: 0x49/0x01`

I have set up the wiring using the guide provided [here](https://shop.pimoroni.com/products/pmw3901-optical-flow-sensor-breakout?variant=27869870358611). I have redone the wiring twice and still am encountering the same error so I am pretty sure it is not a wiring issue. But I will provide pictures of my wiring below. Additionally, I have measured all of the data pins and power pin using an oscilloscope and can see that a proper communication signal is being generated when I run the code, so I know there is not a dead pin or a hardware fault.

The board seems to be powered correctly and I have setup my raspberry pi properly with the OS and done all OS and library upgrades/updates. I have added the proper stuff to the boot config text file to enable all the spi channels. Is there something I am missing? Is my wiring correct? Is there something I am missing in the code / setup? Has someone gotten this to work? Any help would be greatly appreciated.

Thanks
Andrew

Conntetions:

3v-5v ---> 3.3V
CS      ---> BCM 7 / Position 26
SCK    ---> BCM 11 / Position 23
MISO ---> BCM 9   / Position 21
MOSI ---> BCM 10 / Position 19
INT    ---> BCM 19 / Position 35
GND  ---> GND

![image](https://github.com/pimoroni/pmw3901-python/assets/51041426/0a0ab240-b776-451f-88cf-103b31a3b61b)

**Comment by Gadgetoid** [comment]
See details in this PR for installing the - hopefully - fixed library which adds revision 1 to a new list of supported revisions: https://github.com/pimoroni/pmw3901-python/pull/20

Assumes you're in a virtual env or otherwise have a functional "pip".

**Comment by Andrew123098** [comment]
Thank you this fixed the problem.

**Comment by Gadgetoid** [comment]
You're welcome. I've no idea how revision 1 slipped through our post production testing without getting noticed. Will do some sleuthing into that!

**Comment by Andrew123098** [comment]
Thank you for your swift response!! I really appreciate it :)
