### ISSUE TITLE
Device not found when initialized through the PMW3901 class

### ISSUE THREAD

**Issue by blacklight** [pimoroni/pmw3901-python#2]
I have a PMW3901 breakout installed on a RPi4 with breakout garden hat, as shown in the image below:

![IMG_20190815_182849](https://user-images.githubusercontent.com/42405/63111085-37dc7700-bf8d-11e9-83ea-677740589f61.jpg)

When I try to run the [sample code](https://github.com/pimoroni/pmw3901-python/blob/master/examples/motion.py#L21) I get the following error, regardless of the used front/back spi_slot option:

```
Traceback (most recent call last):
  File "motion.py", line 21, in <module>
    flo = PMW3901(spi_port=0, spi_cs=1, spi_cs_gpio=BG_CS_FRONT_BCM if args.spi_slot == 'front' else BG_CS_BACK_BCM)
  File "/usr/local/lib/python3.7/dist-packages/pmw3901/__init__.py", line 24, in __init__
    self.spi_dev.open(spi_port, spi_cs)
FileNotFoundError: [Errno 2] No such file or directory
```

I have also tried multiple combinations of `spi_port` and `spi_cs` but none seemed to work. Is it a known issue? Is there any documented workaround or am I doing anything wrong?

**Comment by Gadgetoid** [comment]
The `spi_cs` value is actually ignored. Could you try changing `spi_cs_gpio` to either `BG_CS_FRONT_BCM` or `BG_CS_BACK_BCM`?

Will flag this issue up as an enhancement, since I think `spi_cs` needs dropping from the class constructor altogether.

**Comment by blacklight** [comment]
Hi @Gadgetoid, I do indeed bump into the same issue regardless of the `spi_cs_gpio` parameter:

```
pi@turing:~$ python motion.py --spi-slot front
motion.py - Detect flow/motion in front of the PMW3901 sensor.

Press Ctrl+C to exit!

Traceback (most recent call last):
  File "motion.py", line 21, in <module>
    flo = PMW3901(spi_port=0, spi_cs=1, spi_cs_gpio=BG_CS_FRONT_BCM if args.spi_slot == 'front' else BG_CS_BACK_BCM)
  File "/usr/local/lib/python3.7/dist-packages/pmw3901/__init__.py", line 24, in __init__
    self.spi_dev.open(spi_port, spi_cs)
FileNotFoundError: [Errno 2] No such file or directory

pi@turing:~$ python motion.py --spi-slot back
motion.py - Detect flow/motion in front of the PMW3901 sensor.

Press Ctrl+C to exit!

Traceback (most recent call last):
  File "motion.py", line 21, in <module>
    flo = PMW3901(spi_port=0, spi_cs=1, spi_cs_gpio=BG_CS_FRONT_BCM if args.spi_slot == 'front' else BG_CS_BACK_BCM)
  File "/usr/local/lib/python3.7/dist-packages/pmw3901/__init__.py", line 24, in __init__
    self.spi_dev.open(spi_port, spi_cs)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by blacklight** [comment]
My bad, I hadn't noticed that the SPI was disabled in /boot/config.txt. After enabling the SPI everything works as expected:

```
dtparam=spi=on
```

There's still indeed a possible enhancement on removing the unused `spi_cs` parameter in the constructor though.

**Comment by roaldarbol** [comment]
I'm getting this error too. SPI is enabled. I'm using the smaller one row Breakout Garden (2xI2C, 1xSPI). I've tried changing `spi_port`, `spi_cs` and `spi_cs_gpio`, but keep getting the same error. I've also tried both with the PWM3901 and the new PAA5100JE breakouts. Any idea what could be going on here?

**Comment by roaldarbol** [comment]
Did a clean OS install and it works now. Not sure what caused it though.

**Comment by floridajohn** [comment]
I also got tripped up by this:
dtparam=spi=on

It was commented out in /boot/config.txt file.  The documentation seems really sparse.
