### ISSUE TITLE
Incorrect default CS Pin

### ISSUE THREAD

**Issue by notreallyaclue** [pimoroni/pmw3901-python#3]
There are inconsistencies in your pin numbering for 'CS'. Your website describes using BCM pin 8 for CS, which corresponds to `BG_CS_BACK_BCM = 8` in the library, ie 'back'.

In the example code it defaults to 'front'

`parser.add_argument('--spi-slot', type=str,
                    **_default='front'_**, choices=['front', 'back'],
                    help='Breakout Garden SPI slot.')

args = parser.parse_args()

flo = PMW3901(spi_port=0, spi_cs=1, spi_cs_gpio=BG_CS_FRONT_BCM **_if args.spi_slot == 'front'_** else BG_CS_BACK_BCM)`

This is probably in line with your breakout hat, so the solution is either:
Change the pin on your website to CS = BCM 7 - This matches your code
Change the default to 'back' - This matches your website.

**Comment by Gadgetoid** [comment]
Thanks for pointing this out. I reckon `front` is probably the sensible default, since the sensor wouldn't be much cop with something else mounted in front of it. I'll see about getting out website changed.
