### ISSUE TITLE
Reading sensor image data?

### ISSUE THREAD

**Issue by JB515** [pimoroni/pmw3901-python#5]
More a query (and possible feature request) than an issue, but I didn't really know where else to ask this...

Is it possible to access the very low resolution image data from the sensor? I have seen registers referring to RawData and shutter so am thinking there is support for this in the chip. Wondered if anyone knows this *isn't* possible for some reason before I start pouring time into trying to make it work?

**Comment by Gadgetoid** [comment]
This is a good question- digging up the *actual* datasheet refers to a "Frame Capture" mode which involves a contrived sequence of register writes followed by grabbing the frame data one byte at a time from the `RawData_Grab` register (up to 1225 bytes) (which I guess makes the sensor 35x35 pixels)

This data would probably only be useful as a curiosity, or to anyone trying to implement their own optical flow sensing algorithm, but if you manage to get it up and running do let me know!
