### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by johnstaveley** [pimoroni/pmw3901-python#9]
I am trying to run this: https://github.com/pimoroni/pmw3901-python/blob/master/examples/motion.py

But it fails on this line:

Traceback (most recent call last):
```
  File "/home/pi/optical_flow_sensor.py", line 19, in <module>
    flo = PMW3901(spi_port=0, spi_cs=1, spi_cs_gpio=BG_CS_FRONT_BCM if args.spi_slot == 'front' else BG_CS_BACK_BCM)
  File "/usr/local/lib/python3.7/dist-packages/pmw3901/__init__.py", line 24, in __init__
    self.spi_dev.open(spi_port, spi_cs)
FileNotFoundError: [Errno 2] No such file or directory
```

I have run:
     sudo pip3 install pmw3901
and rebooted
I have done:
    ls /usr/local/lib/python3.7/dist-packages/pmw3901/
`and can see the file __init__.py is present`

**Comment by Gadgetoid** [comment]
You need to enable SPI. You can do this in the Raspberry Pi Configuration tool, or by running `sudo raspi-config` and enabling it using the menu there.
